Repository connection-2023/backend, pull requests merged in 2024-03, with the labels that each got.

#401 Feat(#158): 패스권 판매 비활성화 기능 구현 완료
  src/pass/controllers/pass.controller.ts
  src/pass/controllers/swagger/pass.swagger.ts
  src/pass/repository/pass.repository.ts
  src/pass/services/pass.service.ts
Labels: feature

#405 Refactor(#250): 검색시 비활성화 된 패스권 검색 결과에서 제외 되도록 수정
  src/search/services/search.service.ts
Labels: refactor

#406 Feat(#19): 패스권 판매 관련 처리 로직 추가
  src/payments/repository/payments.repository.ts
  src/payments/services/payments.service.ts
  src/payments/swagger-decorators/create-pass-payment-info-decorater.ts
Labels: feature, refactor

#408 Feat(#397): 강의 생성 알림 구현
  package-lock.json
  package.json
  src/app.module.ts
  src/chats/chats.module.ts
  src/lecture/lecture.module.ts
  src/lecture/services/lecture.service.ts
  src/notification/controllers/notification.controller.spec.ts
  src/notification/controllers/notification.controller.ts
  src/notification/enum/notification.enum.ts
  src/notification/events/notification.event.ts
  src/notification/events/notification.handler.ts
  src/notification/interfaces/notification.interface.ts
  src/notification/notification.module.ts
  src/notification/repositories/notification.repository.ts
  src/notification/schemas/notification.schema.ts
  src/notification/services/notification.service.spec.ts
  src/notification/services/notification.service.ts
Labels: merge
